### ISSUE TITLE
Using *args as the parameter for the 'combi' function

### ISSUE THREAD

**Issue by GokulramGHV** [thenithinbalaji/pyrandtoys#6]
Instead of giving arguments like this
` combi(['coin', 'dice']) `

By using *args, the arguments can be given like this
` combi('coin', 'dice') `

**Comment by thenithinbalaji** [comment]
Sounds good!

**Comment by thenithinbalaji** [comment]
Added in #8 release
@GokulramGHV

**Comment by thenithinbalaji** [comment]
Both,
combi(['coin', 'dice'])
combi('coin', 'dice')
works
